/* $Id: juin 22, 2016 23:12:45$
 * File is automatically generated by the Xtext language generator. Do not change it.
 *
 */
package io.sarl.lang;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SARLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return io.sarl.lang.ui.internal.SARLActivator.getInstance().getInjector("io.sarl.lang.SARL");
	}

}
