#!/usr/bin/env bash

CDIR=`dirname $0`

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
	# Linux
	if [ -z "$DEVEL_SARL_LAUNCH_SCRIPT" ]; then
		EXEC="$CDIR/products/updatesite/target/products/io.sarl.lang.product/linux/gtk/x86_64/eclipse-sarl-ubuntu.sh"
	else
		EXEC="$DEVEL_SARL_LAUNCH_SCRIPT"
	fi
	if [ -z "$DEVEL_SARL_WORKSPACE" ]; then
		WORKSPACE="$HOME/Documents/Workspaces/runtime-io.sarl.lang.product"
	else
		WORKSPACE="$DEVEL_SARL_WORKSPACE"
	fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
        # Mac OSX
	if [ -z "$DEVEL_SARL_LAUNCH_SCRIPT" ]; then
		EXEC="$CDIR/products/updatesite/target/products/io.sarl.lang.product/macosx/cocoa/x86_64/Eclipse.app/Content/Eclipse/eclipse-sarl-macos.sh"
	else
		EXEC="$DEVEL_SARL_LAUNCH_SCRIPT"
	fi
	if [ -z "$DEVEL_SARL_WORKSPACE" ]; then
		WORKSPACE="$HOME/Documents/Workspaces/runtime-io.sarl.lang.product"
	else
		WORKSPACE="$DEVEL_SARL_WORKSPACE"
	fi
elif [[ "$OSTYPE" == "cygwin" ]]; then
        echo "Unsupported operating system: $OSTYPE" >&2
        exit 255
elif [[ "$OSTYPE" == "msys" ]]; then
	# MinGW
        echo "Unsupported operating system: $OSTYPE" >&2
        exit 255
elif [[ "$OSTYPE" == "win32" ]]; then
	# Standard Windows
        echo "Unsupported operating system: $OSTYPE" >&2
        exit 255
elif [[ "$OSTYPE" == "freebsd"* ]]; then
	# FreeBSD
        echo "Unsupported operating system: $OSTYPE" >&2
        exit 255
else
        echo "Unknown operating system: $OSTYPE" >&2
        exit 255
fi

echo "Running: $EXEC"

if [ -f "$EXEC" ]; then
	if [ -d "$WORKSPACE" ]; then
		echo "Workspace: $WORKSPACE"
		exec bash "$EXEC" -data "$WORKSPACE" "$@"
	else
		exec bash "$EXEC" "$@"
	fi
	exit 0
else
	echo "Executable not found or not runnable. Please re-generate it with:" >&2
	echo "mvn clean install -Dmaven.test.skip=true" >&2
	exit 255
fi

