#!/usr/bin/env bash

CDIR=`dirname $0`

if [ -z "$DEVEL_SARL_DSL_LAUNCH_SCRIPT" ]
then
	EXEC="$CDIR/products/sarl-dsl/target/products/io.sarl.lang.sarl-dsl.product/linux/gtk/x86_64/eclipse-ubuntu.sh"
else
	EXEC="$DEVEL_SARL_DSL_LAUNCH_SCRIPT"
fi

if [ -z "$DEVEL_SARL_WORKSPACE" ]
then
	WORKSPACE="$HOME/Documents/Workspaces/sarl-dsl"
else
	WORKSPACE="$DEVEL_SARL_WORKSPACE"
fi

echo "Running: $EXEC"

if [ -f "$EXEC" ]
then
	if [ -d "$WORKSPACE" ]
	then
		echo "Workspace: $WORKSPACE"
		exec bash "$EXEC" -data "$WORKSPACE" "$@"
	else
		exec bash "$EXEC" "$@"
	fi
else
	echo "Executable not found or not runnable. Please re-generate it with:" >&2
	echo "mvn clean install -Dmaven.test.skip=true" >&2
	exit 255
fi

exit 0
