= How to Release SARL
:toc: right
:toc-placement!:
:hide-uri-scheme:

toc::[]

The steps for releasing SARL are:

== 1) PHASE 1: RELEASE CANDIDATE VERSION

=== 1.1) Upgrade all the versions in the pom files and the Eclipse platform

** Upgrade the Eclipse target platform
** Synchronize the versions in the pom files (plugins and dependencies) with the same version numbers as in the Eclipse target platform.
** Synchronize the versions in the pom files within the `tests/sarl-maven-plugin.tests/src/test/resources/projects` folder.

=== 1.2) Compiling locally without error

     $> rm -rf $HOME/.m2/repository
     $> mvn clean install

=== 1.3) Commit all the changes

=== 1.4) Tag the version

* Tag the version with with `vX.Y.Z-rcN`, where `N` is the release candidate number.
* Push the tag on Github.

=== 1.3) Do manual tests

If a manual test is failing, fix the problem, and go to step 1.2.

=== 1.6) Maven Central Bundles

Test the generation of the  bundles for Maven Central:

     $> ./build-tools/scripts/prepare-bundles-for-central.py

=== 1.7) Javadoc Generation

Test the generation of the Javadoc for the public API (the real generation will be done by the Rake script of the website):

     $> ./build-tools/scripts/generate-aggregate-javadoc.py

== 2) PHASE 2: RELEASE VERSION

=== 2.1) Remove snapshot markers

Remove all the occurrences of `-SNAPSHOT` in all the poms.

CAUTION: Do not remove the `-SNAPSHOT` in the Groovy scripts.

NOTE: This task is automated by the `./build-tools/scripts/prepare-release.py` script when it is called with the following options: `--releaseversion`.

=== 2.2) Update the versions in the Eclipse configurations

* Remove `.qualifier` in the `MANIFEST.MF` files (in `Bundle-Version`).
* Remove `.qualifier` in the `feature.xml` files (in root tag and in the "sarl" and "janus"" plugins references).
* Remove `.qualifier` in the `*.product` files (in root tag and feature tag).
* Remove `.qualifier` in the `category.xml` files (in feature tags, url and version).

NOTE: This task is automated by the `./build-tools/scripts/prepare-release.py` script when it is called with the following options: `--releaseversion`.

=== 2.3) Update General and Contributor Readme Files

Update the content of the files `README.adoc` and `CONTRIBUTING.adoc` for using the new version numbers.

NOTE: This task is automated by the `./build-tools/scripts/prepare-release.py` script when it is called with the following options: `--releaseversion`.

=== 2.4) Update the Javadoc Tags

In the `.sarl` and `.java` files:

* Replace `$FullVersion$` by the current SARL version number, with the release date.
* Replace `$GroupId$` by the group name of the current Maven module.
* Replace `$ArtifactId$` by the artifact name of the current Maven module.
* Replace `$Author$` by the hyperlink of the contributor with the identifier `ID`.

NOTE: This task is automated by the `./build-tools/scripts/prepare-release.py` script when it is called with the following options: `--author`, `--maven`.

=== 2.5) Comment any reference to the Snapshot Maven repository

Into the root `pom.xml`, comment any reference to a snapshot maven repository.

=== 2.6) Update the graphical resources

* **Splash screens**
** Update the picture into the `sarl-data-repository` Git repository:
*** A file `splash.bmp` for the main SARL IDE application with `R8G8B8` configuration (no `A9`)
	to be copied into the module `io.sarl.eclipse`
*** A file `splash.bmp` for the main SARL DSL application with `R8G8B8` configuration (no `A9`)
	to be copied into the module `io.sarl.eclipse-dsl4sarl`
*** Copy the slash screens into the associated modules
*** Find the name of the author of the background image, and update the following files to mention this author:
**** file: `io.sarl.eclipse/OSGI-INF/l10n/bundle.properties`, field: `about.general.text`
**** file: `io.sarl.eclipse-dsl4sarl/OSGI-INF/l10n/bundle.properties`, field: `about.general.text`
* **Picture for the "about" dialog box**
** Update the picture into the `sarl-data-repository` Git repository:
*** The file `eclipse-about-banner.png` for both the main SARL IDE and DSL applications with standard PNG configuration
*** Copy the slash screens into the folders `io.sarl.eclipse/icons` and `io.sarl.eclipse-dsl4sarl/icons`
*** If the author of the background is different than for the splash screen, add the author's name into the properties as explained above
		

=== 2.7) Compiling locally without error

     $> rm -rf $HOME/.m2/repository
     $> mvn clean install

=== 2.8) Check auto-generated files

Check if the `about.mappings` files and the `SARLVersion.java` file are containing the correct version numbers.

=== 2.9) Maven Central Bundles

Prepare the bundles for Maven Central:

     $> ./build-tools/scripts/prepare-bundles-for-central.py

Copy the bundles inside a safe folder for the Phase 3.

=== 2.10) Javadoc Generation

Generate the Javadoc for the public API (the real generation will be done by the Rake script of the website):

     $> ./build-tools/scripts/generate-aggregate-javadoc.py

=== 2.11) Commit and push to Github

     $> git commit
     $> git push --all

=== 2.12) Tag the Git with the version number

     $> git tag "vX.Y.Z"
     $> git push --tags

=== 2.13) Release onto the SARL servers.

For uploading the release files onto the SARL server, you could use the provided script:

     $> ./build-tools/scripts/mvn-release-sarl.py

This script needs to have environment variables for defining the SARL server addresses, and the access login.

     export MAVENSARLIO_URL=dav:https://XXX
     export UPDATESSARLIO_URL=dav:https://YYY
     export MAVENSARLIO_USER=ZZZ


== 3) PHASE 3: DISSEMINATION OF THE RELEASE VERSION

=== 3.1) Maven Central Bundles

Updload the Maven Bundle on Maven Central with http://oss.sonatype.org

=== 3.2) Debian Packages

Create and upload the debian packages.

=== 3.3) Copy on Google Drive

Copy the product, md5 and sha1 files within the Google Drive of SARL.

=== 3.3) Update the ID within Jekill

Get the download IDs of the files within Google Drive and copy them into the file `_config.yml`.
The `confirm` IDs could be obtained by downloading the archive file, then Google should complains about
a too large file, and the confirm ID is inside the download link given by Google Driver after its complain.

=== 3.4) Changelog

Create the "Changes" page for the website, and add a link to the "Changes" page of the previous website inside.
In this way, it will be possible to following the change history from the ealier to older changes.

=== 3.5) Synchronize with other projects

Synchronize the link:https://github.com/sarl/awesome-sarl[Awesome SARL project] with the "Community" page of the website.

=== 3.6) News

Add a "News" in the SARL website.

=== 3.7) Update the SARL website

     $> cd path/to/sarl-site
     $> rake build_full
     $> rake transfer

=== 3.8) Commit and push the website Gits.

=== 3.9) Clean issues

Move all the remaining issues on Github to the following version.

=== 3.10) Close milestones

Close the released milestone on Github.

=== 3.11) Release Notes

Add release notes on Github (from the Changes page on the website), attached to the release tag.

=== 3.12) Wikipedia Review

Review the text on Wikipedia: https://en.wikipedia.org/wiki/SARL_language

=== 3.13) Announcements

Announce the new version of SARL on:

* SARL's Google groups https://groups.google.com/forum/#!forum/sarl
* SARL's Facebook page https://www.facebook.com/sarllanguage/
* SARL Gitter https://gitter.im/sarl/Lobby
* Linked-in https://www.linkedin.com/
* ResearchGate https://www.researchgate.net
* CIAD laboratory Intranet 
* Research mailing lists (bull-ia@gdria.fr, bull-i3@irit.fr, sma@loria.fr, sage-announce@mailman.sage.org, tccc-announce@COMSOC.ORG, ecoop-info@ecoop.org, agents@cs.umbc.edu, pvs@csl.sri.com, mycolleagues@mailman.ufsc.br, icec@listserver.tue.nl, irma-list@irma-international.org, distributed-computing-announce@datasys.cs.iit.edu, stcos-announce@ieee.net, ahsntc-mailing-list@list.trlab.ca, computational.science@lists.iccsa.org, ant-conf@acadia.ca, latincolleagues@mailman.ufsc.br , authors@mailman.ufsc.br , appsem@lists.tcs.ifi.lmu.de, chi-Jobs@acm.org, cl-isabelle-users@lists.cam.ac.uk, clean-list@science.ru.nl, concurrency@listserver.tue.nl, cscw-all@jiscmail.ac.uk, easst-members@lists.le.ac.uk, events@fmeurope.org, gratra@lists.uni-paderborn.de, haskell@haskell.org, announce@aosd.net, multiagent@yahoogroups.com, petrinet@informatik.uni-hamburg.de, prog-lang@cs.uiuc.edu, seworld@sigsoft.org, types-announce@lists.seas.upenn.edu, zforum@comlab.ox.ac.uk, aixia@aixia.it, event-request@in.tu-clausthal.de)

== 4) PHASE 4: DEVELOPMENT VERSION

=== 4.1) Revert versions

Revert steps 2.1 to 2.5; and change the following:

* Version ranges in the `Required-Bundles` of `MANIFEST.MF`.
* Versions in the requirements of `feature.xml` (in root tag and in the "sarl" and "janus"" plugins references).
* Versions in the `*.product` (in root tag and feature tag).
* Versions in the `category.xml` (in feature tags, url and version).
* Uncomment the Snapshot Maven repository.

NOTE: This task is automated by the `./build-tools/scripts/prepare-release.py` script when it is called with the following options: `--develversion` when it is invoked from the "master/snapshot" branch of SARL.

=== 4.2) Upgrade versions

Change the version numbers into the archive files stored in the `io.sarl.tests.testdata` project.

=== 4.3) Change the UI resources.

* **Splash screens**
** Update the picture into the `sarl-data-repository` Git repository:
*** A file `splash.bmp` for the main SARL IDE application with `R8G8B8` configuration (no `A9`)
	to be copied into the module `io.sarl.eclipse`
*** A file `splash.bmp` for the main SARL DSL application with `R8G8B8` configuration (no `A9`)
	to be copied into the module `io.sarl.eclipse-dsl4sarl`
*** Copy the slash screens into the associated modules
*** Find the name of the author of the background image, and update the following files to mention this author:
**** file: `io.sarl.eclipse/OSGI-INF/l10n/bundle.properties`, field: `about.general.text`
**** file: `io.sarl.eclipse-dsl4sarl/OSGI-INF/l10n/bundle.properties`, field: `about.general.text`
* **Picture for the "about" dialog box**
** Update the picture into the `sarl-data-repository` Git repository:
*** The file `eclipse-about-banner.png` for both the main SARL IDE and DSL applications with standard PNG configuration
*** Copy the slash screens into the folders `io.sarl.eclipse/icons` and `io.sarl.eclipse-dsl4sarl/icons`
*** If the author of the background is different than for the splash screen, add the author's name into the properties as explained above

=== 4.4) Compiling locally without error.

     $> rm -rf $HOME/.m2/repository
     $> mvn clean install

=== 4.5) Commit and push to Github:

     $> git commit
     $> git push --all

