= How to Upgadre Eclipse
:toc: right
:toc-placement!:
:hide-uri-scheme:

The steps for upgrading Eclipse into the SARL project are:

== 1. Upgrade Maven Configuration

=== 1.1. Update the root `pom.xml` file

* Upgrade Tycho version: `org.eclipse.tycho:tycho-maven-plugin` on https://search.maven.org/search?q=tycho-maven-plugin[Maven Central].

	<tycho.version>2.7.0</tycho.version>

* Upgrade the version of Xtext that is released with Eclipse. `xtext.Version` is the current version number, as well as `xtext.version.current`.
   `xtext.version.next` is the version number that is not yet supported by SARL. `xtext.version.javadoc` is the version number to appear on the
   API documentation.
   **If the version that is embedded into Eclipse does not corresponds to the one on https://search.maven.org/search?q=g:org.eclipse.xtext[Maven Central], you have to add the P2 repository of Xtext (see next section for details).**

	<xtext.version>2.20.0</xtext.version>
	<xtext.version.current>2.20.0</xtext.version.current>
	<xtext.version.next>2.20.1</xtext.version.next>
	<xtext.version.javadoc>2.20</xtext.version.javadoc>

* Upgrade the version of the SWT livrary: `org.eclipse.platform:org.eclipse.swt.gtk.linux.x86_64` on https://search.maven.org/search?q=org.eclipse.swt.gtk.linux.x86_64[Maven Central].

	<swt.version>3.114.0</swt.version>

* Upgrade the Checkstyle version in order to be the same as the version of Checktyle embedded into the Eclipse product.

	<checkstyle.version>8.32</checkstyle.version>


=== 1.2. Update the Tycho parent pom (`tycho-parent/pom.xml`)

* Change the pointed http://download.eclipse.org/releases[P2 repository] of Eclipse:

	<url>http://download.eclipse.org/releases/2019-12/</url>

* Change the pointed https://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-tycho/[P2 repository] of M2E connectors:

	<url>https://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-tycho/0.8.1/N/LATEST/</url>

* Depending on your need to include a specific version of Xtext, you have to un/comment the Xtext P2 repository:

	<repository>
		<id>org.eclipse.modeling.tmf.xtext.updates</id>
		<layout>p2</layout>
		<url>http://download.eclipse.org/modeling/tmf/xtext/updates/releases/${xtext.version.current}/</url>
	</repository>


= 2. Update the SARL P2 repository

Ensure that the SARL P2 repository provides the correct versions for:

* Guava
* Guice
* Google Gson
  

== 3. Upgrade Eclipse Configuration

* Launch the SARL-DSL product
* Edit the target platform (usually Eclipse plugins and Xtext plugins have changed their versions)
** Change the referenced repositories if a version number is included into the URL
* Edit the dependency versions in all of the `MANIFEST.MF` of the Eclipse plugins
* Update the version (compute dependencies) into all the `feature.xml`
* Check the dependency tree of the SARL product by clicking on the checking button of the product editor

== 4. Fix the core code

* Compile

	$> mvn clean install -Dmaven.test.skip=true

* Re-generate the SARL compiler from its grammar (in case the Xtext infrastructure has changed something into its generation process).
** Launch the MWE2 script on the project `io.sarl.lang.mwe2`
* Check if Xtext-based bug fixes are also applied in Xtext.
** See content of the packages `<package-name>/bugfixes` in all the Eclipse plugins and Maven modules.
* Compile again

	$> mvn clean install -Dmaven.test.skip=true


== 5. Fix the test code

* Compile and run all the tests

	$> mvn clean install



== 6. Commit and publish

* Commit the changes with an appropriate message.
* Push the Git.


