<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sarl" nsURI="http://www.sarl.io/lang/SARL" nsPrefix="sarl">
  <eClassifiers xsi:type="ecore:EClass" name="SarlScript" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="SarlField" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendField"/>
  <eClassifiers xsi:type="ecore:EClass" name="SarlBreakExpression" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 0.5"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SarlContinueExpression" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 0.7"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SarlAssertExpression" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 0.6"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SarlAction" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="firedEvents" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SarlConstructor" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendConstructor"/>
  <eClassifiers xsi:type="ecore:EClass" name="SarlBehaviorUnit" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendMember">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmParameterizedTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SarlCapacityUses" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendMember">
    <eStructuralFeatures xsi:type="ecore:EReference" name="capacities" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmParameterizedTypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SarlRequiredCapacity" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendMember">
    <eStructuralFeatures xsi:type="ecore:EReference" name="capacities" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmParameterizedTypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SarlClass" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="SarlInterface" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendInterface"/>
  <eClassifiers xsi:type="ecore:EClass" name="SarlEnumeration" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendEnum"/>
  <eClassifiers xsi:type="ecore:EClass" name="SarlAnnotationType" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendAnnotationType"/>
  <eClassifiers xsi:type="ecore:EClass" name="SarlEnumLiteral" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendEnumLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="SarlEvent" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendTypeDeclaration">
    <eOperations name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmParameterizedTypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass"
                name="SarlCastedExpression"
                eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XCastedExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@since 0.9"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference"
                         name="feature"
                         eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmOperation"
                         containment="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation"
                 value="Provide the feature to call in casting the value to target type."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference"
                         name="receiver"
                         eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
                         containment="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation"
                 value="Provide the receiver for the call to the feature, or null if the default should be applied."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference"
                         name="argument"
                         eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
                         containment="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation"
                 value="Provide the argument to pass to the feature, or null if the feature does not need to have argument."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SarlSpace" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendTypeDeclaration">
    <eOperations name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmParameterizedTypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SarlArtifact" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendTypeDeclaration">
    <eOperations name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmParameterizedTypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SarlAgent" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendTypeDeclaration">
    <eOperations name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isStrictFloatingPoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmParameterizedTypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SarlCapacity" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendTypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmParameterizedTypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SarlBehavior" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendTypeDeclaration">
    <eOperations name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isStrictFloatingPoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmParameterizedTypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SarlSkill" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendTypeDeclaration">
    <eOperations name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isStrictFloatingPoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmParameterizedTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implements" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmParameterizedTypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SarlFormalParameter" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
