= Developpers tools
:toc: right
:toc-placement!:
:hide-uri-scheme:

toc::[]

== 1. Eclipse IDE

All the configuration files related to the Eclipse IDE are stored into the "eclipse" folder of this module.

=== 1.1. Install the Eclipse preferences

The SARL developers use a specific set of preferences into the Eclipse IDE in order to have the same level of quality of the implementation.
You could import into your own Eclipse IDE the preferences that are considered as standard by the SARL developers.

The preferences' definition is in the file `201903_preferences.epf`, where `201903` denotes the supported version of the Eclipse IDE.

For importing the preferences, follow the points below:
* Open your Eclipse DSL environment
* Open the menu `File > Import...`
* Open the folder `General`, select `Preferences`, and click on `Next`.
* Browse to the preference file that is mentionned above, and click on `Finish`.

CAUTION: The provided preferences cover all the modules of the Eclipse IDE, including code style formating, import order, warnings' levels, etc. If you are interested only by the order of the imports, please import the file `eclipse.importorder`.


=== 1.2. Install the working sets

By default, when you import the SARL project's modules into your workspace, all the projects are located into the "Other" working set into the "Package Explorer".
This is not a convinient view of the SARL project's modules. In order to solve this issue, you could use the working set defining that will dispatch the
SARL project's modules into different working sets.

The predefined working set definition is in the file `workingsets.xml`.

Copy the file `workingsets.xml` into `${workspace_loc}/.metadata/.plugins/org.eclipse.ui.workbench/workingsets.xml`, where `${workspace_loc}` is the path to
the workspace in which you have imported the SARL project.

CAUTION: Copy the working set definition must be done without a running Eclipse.

CAUTION: The existing definition of the working sets will be replaced by the content of the copied file.

