/*
 * $Id$
 *
 * File is automatically generated by the Xtext language generator.
 * Do not change it.
 *
 * SARL is an general-purpose agent programming language.
 * More details on http://www.sarl.io
 *
 * Copyright (C) 2014-2024 SARL.io, the Original Authors and Main Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.sarl.lang.codebuilder.builders;

import io.sarl.lang.sarl.SarlAction;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.common.types.JvmType;
import org.eclipse.xtext.common.types.JvmTypeReference;
import org.eclipse.xtext.common.types.access.IJvmTypeProvider;
import org.eclipse.xtext.xbase.lib.Pure;

/** Builder of a Sarl SarlAction.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 117
 */
@SuppressWarnings("all")
public interface ISarlActionBuilder {

	/** Find the reference to the type with the given name.
	 * @param typeName the fully qualified name of the type
	 * @return the type reference.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 403
	 */
	JvmTypeReference newTypeRef(String typeName);

	/** Find the reference to the type with the given name.
	 * @param context the context for the type reference use
	 * @param typeName the fully qualified name of the type
	 * @return the type reference.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 431
	 */
	JvmTypeReference newTypeRef(Notifier context, String typeName);

	/** Find the reference to the type and type parameters.
	 * @param type the type to reference
	 * @param args the type arguments to put in the reference to the given type
	 * @return the type reference.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 461
	 */
	JvmTypeReference newTypeRef(JvmType type, JvmTypeReference... args);

	/** Find the reference to the type and type parameters.
	 * @param type the type to reference
	 * @param args the type arguments to put in the reference to the given type
	 * @return the type reference.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 493
	 */
	JvmTypeReference newTypeRef(Class type, JvmTypeReference... args);

	/** Find the reference to the type and type parameters.
	 * @param context the context in which the type is defined
	 * @param type the type to reference
	 * @param args the type arguments to put in the reference to the given type
	 * @return the type reference.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 527
	 */
	JvmTypeReference newTypeRef(Notifier context, Class type, JvmTypeReference... args);

	/** Dispose the resource.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 557
	 */
	void dispose();

	/** Replies the context for type resolution.
	 * @return the context or {@code null} if the Ecore object is the context.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 582
	 */
	IJvmTypeProvider getTypeResolutionContext();

	/** Initialize the Ecore element.
	 * @param container the container of the SarlAction.
	 * @param name the name of the SarlAction.
	 * @param modifier the major/default modifier to be associated to the member.
	 * @param context the context in which type resolution must be applied.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 629
	 */
	void eInit(EObject container, String name, String modifier, IJvmTypeProvider context);

	/** Replies the generated element.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 959
	 */
	@Pure
	SarlAction getSarlAction();

	/** Replies the resource.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 993
	 */
	@Pure
	Resource eResource();

	/** Change the documentation of the element.
	 *
	 * <p>The documentation will be displayed just before the element.
	 *
	 * @param doc the documentation.
	 * @return {@code this}.
	 * @see AbstractSubCodeBuilderFragment.java : appendTo : 602
	 */
	ISarlActionBuilder setDocumentation(String doc);

	/** Add a formal parameter.
	 * @param name the name of the formal parameter.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1111
	 */
	IFormalParameterBuilder addParameter(String name);

	/** Add a throwable exception.
	 * @param type the fully qualified name of the exception.
	 * @return {@code this}
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1155
	 */
	ISarlActionBuilder addException(String type);

	/** Add a throwable exception.
	 * @param type the exception.
	 * @return {@code this}
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1198
	 */
	ISarlActionBuilder addException(JvmTypeReference type);

	/** Add a fired event.
	 * @param type the fully qualified name of the event.
	 * @return {@code this}
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1243
	 */
	ISarlActionBuilder addFiredEvent(String type);

	/** Add a fired event.
	 * @param type the event.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1284
	 */
	void addFiredEvent(JvmTypeReference type);

	/** Change the return type.
	 @param type the return type of the member.
	 * @return {@code this}
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1326
	 */
	ISarlActionBuilder setReturnType(String type);

	/** Change the return type.
	 @param type the return type of the member.
	 * @return {@code this}
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1382
	 */
	ISarlActionBuilder setReturnType(JvmTypeReference type);

	/** Create the block of code.
	 * @return the block builder.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1442
	 */
	IBlockExpressionBuilder getExpression();

	/** Add an annotation.
	 * @param type the qualified name of the annotation
	 * @return {@code this}
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1505
	 */
	ISarlActionBuilder addAnnotation(String type);

	/** Add an annotation.
	 * @param type the annotation type
	 * @return {@code this}
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1549
	 */
	ISarlActionBuilder addAnnotation(JvmTypeReference type);

	/** Add a modifier.
	 * @param modifier the modifier to add.
	 * @return {@code this}
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1599
	 */
	ISarlActionBuilder addModifier(String modifier);

	/** Add a type parameter.
	 * @param name the simple name of the type parameter.
	 * @return the builder of type parameter.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1680
	 */
	ITypeParameterBuilder addTypeParameter(String name);

}

