/*
 * $Id$
 *
 * File is automatically generated by the Xtext language generator.
 * Do not change it.
 *
 * SARL is an general-purpose agent programming language.
 * More details on http://www.sarl.io
 *
 * Copyright (C) 2014-2025 SARL.io, the Original Authors and Main Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.sarl.lang.codebuilder.builders;

import com.google.inject.Inject;
import com.google.inject.Provider;
import io.sarl.lang.sarl.SarlAnnotationType;
import io.sarl.lang.sarl.SarlFactory;
import io.sarl.lang.sarl.SarlScript;
import java.util.function.Predicate;
import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.xtend.core.xtend.XtendFactory;
import org.eclipse.xtend.core.xtend.XtendTypeDeclaration;
import org.eclipse.xtext.common.types.JvmDeclaredType;
import org.eclipse.xtext.common.types.JvmTypeReference;
import org.eclipse.xtext.common.types.access.IJvmTypeProvider;
import org.eclipse.xtext.util.EmfFormatter;
import org.eclipse.xtext.util.Strings;
import org.eclipse.xtext.xbase.compiler.DocumentationAdapter;
import org.eclipse.xtext.xbase.lib.Pure;

/** Builder of a Sarl SarlAnnotationType.
	 * @see TopElementBuilderFragment.java : appendTo : 410
 */
@SuppressWarnings("all")
public class SarlAnnotationTypeBuilderImpl extends AbstractBuilder implements ISarlAnnotationTypeBuilder {

	private SarlAnnotationType sarlAnnotationType;

	private EObject container;

	/**
	 * @see TopElementBuilderFragment.java : appendTo : 1625
	 */
	@Override
	@Pure
	public String toString() {
		return EmfFormatter.objToStr(getSarlAnnotationType());
	}

	/** Initialize the Ecore element when inside a script.
	 * @param script the SARL script in which this SarlAnnotationType is added.
	 * @param name the simple name of the SarlAnnotationType.
	 * @param context the context in which the resolution of types must be done.
	 * @see TopElementBuilderFragment.java : appendTo : 1662
	 */
	public void eInit(SarlScript script, String name, IJvmTypeProvider context) {
		setTypeResolutionContext(context);
		if (this.sarlAnnotationType == null) {
			this.container = script;
			this.sarlAnnotationType = SarlFactory.eINSTANCE.createSarlAnnotationType();
			this.sarlAnnotationType.setAnnotationInfo(XtendFactory.eINSTANCE.createXtendTypeDeclaration());
			this.sarlAnnotationType.setName(name);
			script.getXtendTypes().add(this.sarlAnnotationType);
		}
	}

	/** Initialize the Ecore element when inner type declaration.
	 * @param container the Ecore type that must contain this new SarlAnnotationType.
	 * @param name the simple name of the SarlAnnotationType.
	 * @param context the context in which the resolution of types must be done.
	 * @see TopElementBuilderFragment.java : appendTo : 1741
	 */
	public void eInit(XtendTypeDeclaration container, String name, IJvmTypeProvider context) {
		setTypeResolutionContext(context);
		if (this.sarlAnnotationType == null) {
			this.container = container;
			this.sarlAnnotationType = SarlFactory.eINSTANCE.createSarlAnnotationType();
			this.sarlAnnotationType.setName(name);
			container.getMembers().add(this.sarlAnnotationType);
		}
	}

	/** Replies the generated SarlAnnotationType.
	 * @see TopElementBuilderFragment.java : appendTo : 1798
	 */
	@Pure
	public SarlAnnotationType getSarlAnnotationType() {
		return this.sarlAnnotationType;
	}

	/** Replies the reference to the generated SarlAgent.
	 * @since 0.15
	 * @see TopElementBuilderFragment.java : appendTo : 1838
	 */
	@Pure
	public JvmTypeReference getSarlAnnotationTypeReference() {
		SarlAnnotationType ecoreObject = getSarlAnnotationType();
		return getTypeReferenceFor(ecoreObject);
	}

	/** Replies the JVM declared type for this generated SarlAnnotationType.
	 * @return the type, never {@code null}.
	 * @since 0.15
	 * @see TopElementBuilderFragment.java : appendTo : 1893
	 */
	@Pure
	public JvmDeclaredType getJvmDeclaredType() {
		return getAssociatedElement(JvmDeclaredType.class, getSarlAnnotationType(), eResource(), true);
	}

	/** Replies the resource to which the SarlAnnotationType is attached.
	 * @see TopElementBuilderFragment.java : appendTo : 1928
	 */
	@Pure
	public Resource eResource() {
		return getSarlAnnotationType().eResource();
	}

	/** Change the documentation of the element.
	 *
	 * <p>The documentation will be displayed just before the element.
	 *
	 * @param doc the documentation.
	 * @return {@code this}.
	 * @see AbstractSubCodeBuilderFragment.java : appendTo : 602
	 */
	public ISarlAnnotationTypeBuilder setDocumentation(String doc) {
		if (Strings.isEmpty(doc)) {
			getSarlAnnotationType().eAdapters().removeIf(new Predicate<Adapter>() {
				public boolean test(Adapter adapter) {
					return adapter.isAdapterForType(DocumentationAdapter.class);
				}
			});
		} else {
			DocumentationAdapter adapter = (DocumentationAdapter) EcoreUtil.getExistingAdapter(
					getSarlAnnotationType(), DocumentationAdapter.class);
			if (adapter == null) {
				adapter = new DocumentationAdapter();
				getSarlAnnotationType().eAdapters().add(adapter);
			}
			adapter.setDocumentation(doc);
		}
		return this;
	}

	/** Add a modifier.
	 * @param modifier the modifier to add.
	 * @return {@code this}.
	 * @see TopElementBuilderFragment.java : appendTo : 2492
	 */
	public ISarlAnnotationTypeBuilder addModifier(String modifier) {
		if (!Strings.isEmpty(modifier)) {
			this.sarlAnnotationType.getModifiers().add(modifier);
		}
		return this;
	}

	/**
	 * @see TopElementBuilderFragment.java : appendTo : 523
	 */
	@Inject
	private Provider<ISarlFieldBuilder> iSarlFieldBuilderProvider;

	/** Create a SarlField.
	 * @param name the name of the SarlField.
	 * @return the builder.
	 * @see TopElementBuilderFragment.java : appendTo : 564
	 */
	public ISarlFieldBuilder addVarSarlField(String name) {
		ISarlFieldBuilder builder = this.iSarlFieldBuilderProvider.get();
		builder.eInit(getSarlAnnotationType(), name, "var", getTypeResolutionContext());
		return builder;
	}

	/** Create a SarlField.
	 * @param name the name of the SarlField.
	 * @return the builder.
	 * @see TopElementBuilderFragment.java : appendTo : 564
	 */
	public ISarlFieldBuilder addValSarlField(String name) {
		ISarlFieldBuilder builder = this.iSarlFieldBuilderProvider.get();
		builder.eInit(getSarlAnnotationType(), name, "val", getTypeResolutionContext());
		return builder;
	}

	/** Create a SarlField.	 *
	 * <p>This function is equivalent to {@link #addVarSarlField}.
	 * @param name the name of the SarlField.
	 * @return the builder.
	 * @see TopElementBuilderFragment.java : appendTo : 706
	 */
	public ISarlFieldBuilder addSarlField(String name) {
		return this.addVarSarlField(name);
	}

	/**
	 * @see TopElementBuilderFragment.java : appendTo : 523
	 */
	@Inject
	private Provider<ISarlClassBuilder> iSarlClassBuilderProvider;

	/** Create a SarlClass.
	 * @param name the name of the SarlClass.
	 * @return the builder.
	 * @see TopElementBuilderFragment.java : appendTo : 564
	 */
	public ISarlClassBuilder addSarlClass(String name) {
		ISarlClassBuilder builder = this.iSarlClassBuilderProvider.get();
		builder.eInit(getSarlAnnotationType(), name, getTypeResolutionContext());
		return builder;
	}

	/**
	 * @see TopElementBuilderFragment.java : appendTo : 523
	 */
	@Inject
	private Provider<ISarlInterfaceBuilder> iSarlInterfaceBuilderProvider;

	/** Create a SarlInterface.
	 * @param name the name of the SarlInterface.
	 * @return the builder.
	 * @see TopElementBuilderFragment.java : appendTo : 564
	 */
	public ISarlInterfaceBuilder addSarlInterface(String name) {
		ISarlInterfaceBuilder builder = this.iSarlInterfaceBuilderProvider.get();
		builder.eInit(getSarlAnnotationType(), name, getTypeResolutionContext());
		return builder;
	}

	/**
	 * @see TopElementBuilderFragment.java : appendTo : 523
	 */
	@Inject
	private Provider<ISarlEnumerationBuilder> iSarlEnumerationBuilderProvider;

	/** Create a SarlEnumeration.
	 * @param name the name of the SarlEnumeration.
	 * @return the builder.
	 * @see TopElementBuilderFragment.java : appendTo : 564
	 */
	public ISarlEnumerationBuilder addSarlEnumeration(String name) {
		ISarlEnumerationBuilder builder = this.iSarlEnumerationBuilderProvider.get();
		builder.eInit(getSarlAnnotationType(), name, getTypeResolutionContext());
		return builder;
	}

	/**
	 * @see TopElementBuilderFragment.java : appendTo : 523
	 */
	@Inject
	private Provider<ISarlAnnotationTypeBuilder> iSarlAnnotationTypeBuilderProvider;

	/** Create a SarlAnnotationType.
	 * @param name the name of the SarlAnnotationType.
	 * @return the builder.
	 * @see TopElementBuilderFragment.java : appendTo : 564
	 */
	public ISarlAnnotationTypeBuilder addSarlAnnotationType(String name) {
		ISarlAnnotationTypeBuilder builder = this.iSarlAnnotationTypeBuilderProvider.get();
		builder.eInit(getSarlAnnotationType(), name, getTypeResolutionContext());
		return builder;
	}

}

