/*
 * $Id$
 *
 * File is automatically generated by the Xtext language generator.
 * Do not change it.
 *
 * SARL is an general-purpose agent programming language.
 * More details on http://www.sarl.io
 *
 * Copyright (C) 2014-2024 SARL.io, the Original Authors and Main Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.sarl.lang.codebuilder.builders;

import com.google.inject.Inject;
import com.google.inject.Provider;
import io.sarl.lang.sarl.SarlFactory;
import io.sarl.lang.sarl.SarlProtocolMessage;
import java.util.function.Predicate;
import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.xtend.core.xtend.XtendFactory;
import org.eclipse.xtend.core.xtend.XtendTypeDeclaration;
import org.eclipse.xtext.common.types.access.IJvmTypeProvider;
import org.eclipse.xtext.util.EmfFormatter;
import org.eclipse.xtext.util.Strings;
import org.eclipse.xtext.xbase.compiler.DocumentationAdapter;
import org.eclipse.xtext.xbase.lib.Pure;

/** Builder of a Sarl SarlProtocolMessage.
 * AbstractMemberBuilderFragment.java : appendTo : 154 */
@SuppressWarnings("all")
public class SarlProtocolMessageBuilderImpl extends AbstractBuilder implements ISarlProtocolMessageBuilder {

	/**
	 * @see AbstractMemberBuilderFragment.java : appendTo : 358
	 */
	private EObject container;

	/**
	 * @see AbstractMemberBuilderFragment.java : appendTo : 364
	 */
	private SarlProtocolMessage sarlProtocolMessage;

	/**
	 * @see AbstractMemberBuilderFragment.java : appendTo : 382
	 */
	@Inject
	private Provider<ISarlProtocolParameterBuilder> sarlProtocolParameterBuilderProvider;

	/** Initialize the Ecore element.
	 * @param container the container of the SarlProtocolMessage.
	 * @param name the name of the SarlProtocolMessage.
	 * @param context the context in which type resolution must be applied.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 629
	 */
	public void eInit(EObject container, String name, IJvmTypeProvider context) {
		// Generator code: AbstractMemberBuilderFragment.java : appendTo : 739
		if (this.sarlProtocolMessage == null) {
			this.sarlProtocolMessage = SarlFactory.eINSTANCE.createSarlProtocolMessage();
			internalEInit(container, context);
			this.sarlProtocolMessage.setName(name);
		}
	}

	private void internalEInit(EObject container, IJvmTypeProvider context) {
		// Generator code: AbstractMemberBuilderFragment.java : appendTo : 916
		assert this.sarlProtocolMessage != null;
		setTypeResolutionContext(context);
		this.container = container;
		this.sarlProtocolMessage.setAnnotationInfo(XtendFactory.eINSTANCE.createXtendMember());
		if (container instanceof XtendTypeDeclaration typeDeclaration) {
			typeDeclaration.getMembers().add(this.sarlProtocolMessage);
			this.sarlProtocolMessage.setDeclaringType(typeDeclaration);
		}
	}

	/** Replies the generated element.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 959
	 */
	@Pure
	public SarlProtocolMessage getSarlProtocolMessage() {
		return this.sarlProtocolMessage;
	}

	/** Replies the resource.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 993
	 */
	@Pure
	public Resource eResource() {
		return getSarlProtocolMessage().eResource();
	}

	/** Change the documentation of the element.
	 *
	 * <p>The documentation will be displayed just before the element.
	 *
	 * @param doc the documentation.
	 * @return {@code this}.
	 * @see AbstractSubCodeBuilderFragment.java : appendTo : 602
	 */
	public ISarlProtocolMessageBuilder setDocumentation(String doc) {
		if (Strings.isEmpty(doc)) {
			getSarlProtocolMessage().eAdapters().removeIf(new Predicate<Adapter>() {
				public boolean test(Adapter adapter) {
					return adapter.isAdapterForType(DocumentationAdapter.class);
				}
			});
		} else {
			DocumentationAdapter adapter = (DocumentationAdapter) EcoreUtil.getExistingAdapter(
					getSarlProtocolMessage(), DocumentationAdapter.class);
			if (adapter == null) {
				adapter = new DocumentationAdapter();
				getSarlProtocolMessage().eAdapters().add(adapter);
			}
			adapter.setDocumentation(doc);
		}
		return this;
	}

	/** Add a modifier.
	 * @param modifier the modifier to add.
	 * @return {@code this}
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1599
	 */
	public ISarlProtocolMessageBuilder addModifier(String modifier) {
		if (!Strings.isEmpty(modifier)) {
			getSarlProtocolMessage().getModifiers().add(modifier);
		}
		return this;
	}

	/**
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1635
	 */
	@Override
	@Pure
	public String toString() {
		return EmfFormatter.objToStr(getSarlProtocolMessage());
	}

	/** Add a parameter of type {@code io.sarl.lang.sarl.SarlProtocolParameter}.
	 * @param name the name of the parameter
	 * @return the builder for the parameter, never {@code null}.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1791
	 */
	public ISarlProtocolParameterBuilder addParameter(String name) {
		ISarlProtocolParameterBuilder builder = this.sarlProtocolParameterBuilderProvider.get();
		builder.eInit(this.sarlProtocolMessage, name, getTypeResolutionContext());
		if (!(this.sarlProtocolMessage instanceof XtendTypeDeclaration)) {
			this.sarlProtocolMessage.getParameters().add(builder.getSarlProtocolParameter());
		}
		return builder;

	}

}

