/*
 * $Id$
 *
 * File is automatically generated by the Xtext language generator.
 * Do not change it.
 *
 * SARL is an general-purpose agent programming language.
 * More details on http://www.sarl.io
 *
 * Copyright (C) 2014-2025 SARL.io, the Original Authors and Main Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.sarl.lang.codebuilder.appenders;

import io.sarl.lang.codebuilder.builders.IExpressionBuilder;
import io.sarl.lang.codebuilder.builders.ISarlFieldBuilder;
import io.sarl.lang.sarl.SarlField;
import java.io.IOException;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.common.types.JvmType;
import org.eclipse.xtext.common.types.JvmTypeReference;
import org.eclipse.xtext.common.types.access.IJvmTypeProvider;
import org.eclipse.xtext.xbase.compiler.ISourceAppender;
import org.eclipse.xtext.xbase.lib.Pure;

/** Source appender of a Sarl SarlField.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 194
 */
@SuppressWarnings("all")
public class SarlFieldSourceAppender extends AbstractSourceAppender implements ISarlFieldBuilder {

	private final ISarlFieldBuilder builder;

	public SarlFieldSourceAppender(ISarlFieldBuilder builder) {
		this.builder = builder;
	}

	/** Fill the given receiver with the serialization of the element that is associated to this appender.
	 *
	 * @param appender the receiver of the source code.
	 * @throws IOException if there is error during the serialization.
	 * @see AbstractSubCodeBuilderFragment.java : appendTo : 549
	 */
	public void build(ISourceAppender appender) throws IOException {
		build(this.builder.getSarlField(), appender);
	}

	/** Find the reference to the type with the given name.
	 * @param typeName the fully qualified name of the type
	 * @return the type reference.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 406
	 */
	public JvmTypeReference newTypeRef(String typeName) {
		return this.builder.newTypeRef(typeName);
	}

	/** Find the reference to the type with the given name.
	 * @param context the context for the type reference use
	 * @param typeName the fully qualified name of the type
	 * @return the type reference.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 434
	 */
	public JvmTypeReference newTypeRef(Notifier context, String typeName) {
		return this.builder.newTypeRef(context, typeName);
	}

	/** Find the reference to the type and type parameters.
	 * @param type the type to reference
	 * @param args the type arguments to put in the reference to the given type
	 * @return the type reference.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 464
	 */
	public JvmTypeReference newTypeRef(JvmType type, JvmTypeReference... args) {
		return this.builder.newTypeRef(type, args);
	}

	/** Find the reference to the type and type parameters.
	 * @param type the type to reference
	 * @param args the type arguments to put in the reference to the given type
	 * @return the type reference.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 496
	 */
	public JvmTypeReference newTypeRef(Class type, JvmTypeReference... args) {
		return this.builder.newTypeRef(type, args);
	}

	/** Find the reference to the type and type parameters.
	 * @param context the context in which the type is defined
	 * @param type the type to reference
	 * @param args the type arguments to put in the reference to the given type
	 * @return the type reference.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 530
	 */
	public JvmTypeReference newTypeRef(Notifier context, Class type, JvmTypeReference... args) {
		return this.builder.newTypeRef(context, type, args);
	}

	/** Dispose the resource.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 569
	 */
	public void dispose() {
		this.builder.dispose();
	}

	/** Replies the context for type resolution.
	 * @return the context or {@code null} if the Ecore object is the context.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 598
	 */
	public IJvmTypeProvider getTypeResolutionContext() {
		return this.builder.getTypeResolutionContext();
	}

	/** Initialize the Ecore element.
	 * @param container the container of the SarlField.
	 * @param name the name of the SarlField.
	 * @param modifier the major/default modifier to be associated to the member.
	 * @param context the context in which type resolution must be applied.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 632
	 */
	public void eInit(EObject container, String name, String modifier, IJvmTypeProvider context) {
		this.builder.eInit(container, name, modifier, context);
	}

	/** Replies the generated element.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 962
	 */
	@Pure
	public SarlField getSarlField() {
		return this.builder.getSarlField();
	}

	/** Replies the resource.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 996
	 */
	@Pure
	public Resource eResource() {
		return getSarlField().eResource();
	}

	/** Change the documentation of the element.
	 *
	 * <p>The documentation will be displayed just before the element.
	 *
	 * @param doc the documentation.
	 * @return {@code this}.
	 * @see AbstractSubCodeBuilderFragment.java : appendTo : 602
	 */
	public ISarlFieldBuilder setDocumentation(String doc) {
		this.builder.setDocumentation(doc);
		return this;
	}

	/** Change the type.
	 * @param type the type of the member.
	 * @return {@code this}
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1030
	 */
	public ISarlFieldBuilder setType(String type) {
		this.builder.setType(type);
		return this;
	}

	/** Change the type.
	 * @param type the type of the member.
	 * @return {@code this}
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1072
	 */
	public ISarlFieldBuilder setType(JvmTypeReference type) {
		this.builder.setType(type);
		return this;
	}

	/** Add a modifier.
	 * @param modifier the modifier to add.
	 * @return {@code this}
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1602
	 */
	public ISarlFieldBuilder addModifier(String modifier) {
		this.builder.addModifier(modifier);
		return this;
	}

	/**
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1638
	 */
	@Override
	@Pure
	public String toString() {
		return this.builder.toString();
	}

	/** Replies the initialValue.
	 * @return the value of the initialValue. It may be {@code null}.
	 * @see AbstractMemberBuilderFragment.java : appendTo : 1729
	 */
	@Pure
	public IExpressionBuilder getInitialValue() {
		return this.builder.getInitialValue();
	}

}

