/* $Id: oct. 19, 2015 10:05:53$
 * File is automatically generated by the Xtext language generator. Do not change it.
 *
 */
package io.sarl.lang.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import io.sarl.lang.ui.internal.SARLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SARLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SARLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SARLActivator.getInstance().getInjector(SARLActivator.IO_SARL_LANG_SARL);
	}
	
}
