## Legal Notice

* Specification: SARL General-purpose Agent-Oriented Programming Language ("Specification")
* Version: [:sarl.specification.release_version!]
* Status: [:sarl.specification.release_status!]
* Release: [:sarl.specification.release_date!]

> Copyright &copy; [:project.inceptionYear!]-[:year!] [[:copyrighters!]]([:sarlUrl!]/about/index.html).
>
> Licensed under the Apache License, Version 2.0;
> you may not use this file except in compliance with the License.
> You may obtain a copy of the [License](http://www.apache.org/licenses/LICENSE-2.0).
>
> You are free to reproduce the content of this page on copyleft websites such as Wikipedia.

<small>Generated with the translator [:generator.name!] [:generator.version!].</small>

[:Fact:]{"[:sarl.specification.release_status!]" == "Stable Release" || "[:sarl.specification.release_status!]" == "Draft Release"}
[:Fact:]{"[:sarl.specification.release_date!]".shouldBeDate("YYYY-mm-dd")}
[:Fact:]{"[:project.inceptionYear!]".shouldBeNumber}
[:Fact:]{"[:year!]".shouldBeNumber}
