---
name: "Periodic Full Tests"

on:
  schedule:
    - cron: '27 17 * * 4'

jobs:
  CompileOnLinux:
    name: Testing on Linux
    runs-on: 'ubuntu-latest'
    timeout-minutes: 360
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Selecting Java Version
      uses: actions/setup-java@v4
      with:
        distribution: oracle
        java-version: 21
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.11
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.13
    - name: Cache Maven packages
      uses: actions/cache@v4
      continue-on-error: true
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ matrix.language }}
          ${{ runner.os }}-maven-
    - run: |
         echo "Run, Build and Test using script"
         python ./build-all.py

