## Legal Notice

* Specification: SARL General-purpose Agent-Oriented Programming Language ("Specification")
* Version: [:sarl.specification.release_version!]
* Status: [:sarl.specification.release_status!]
* Release: [:sarl.specification.release_date!]

> Copyright &copy; [:sarl.inception.year!]-[:sarl.last.year!] [[:sarl.copyrighters!]]([:sarl.url!]/about/index.html).
>
> Documentation text and medias are licensed under the Creative Common CC-BY-SA-4.0;
> you may not use this file except in compliance with CC-BY-SA-4.0.
> You may obtain a copy of [CC-BY-4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.en).
>
> Examples of SARL code are licensed under the Apache License, Version 2.0;
> you may not use this file except in compliance with the Apache License.
> You may obtain a copy of the [Apache License](http://www.apache.org/licenses/LICENSE-2.0).
>
> You are free to reproduce the content of this page on copyleft websites such as Wikipedia.

<small>Generated with the translator [:generator.name!] [:generator.version!].</small>

[:Fact:]{"[:sarl.specification.release_status!]" == "Stable Release" || "[:sarl.specification.release_status!]" == "Draft Release"}
[:Fact:]{"[:sarl.specification.release_date!]".shouldBeDate("YYYY-mm-dd")}
[:Fact:]{"[:sarl.inception.year!]".shouldBeNumber}
[:Fact:]{"[:sarl.last.year!]".shouldBeNumber}
